"""Adapter protocols shared across CST integrations."""
from __future__ import annotations
from typing import Iterable, Protocol, runtime_checkable
from cstlib.core import Event
@runtime_checkable
class ModelAdapter(Protocol):
    name: str
    def __call__(self, message: str, context: dict[str, object]) -> str: ...
    def health(self) -> dict[str, object]: ...
@runtime_checkable
class EmbeddingAdapter(Protocol):
    name: str
    def __call__(self, text: str) -> Iterable[float]: ...
    def health(self) -> dict[str, object]: ...
@runtime_checkable
class SensorAdapter(Protocol):
    name: str
    def sample(self) -> Event: ...
    def health(self) -> dict[str, object]: ...
@runtime_checkable
class EntropyAdapter(Protocol):
    name: str
    def sample(self, nbytes: int = 32): ...
    def health(self) -> dict[str, object]: ...
class AdapterError(RuntimeError): pass
